### ISSUE TITLE
Add support for `v1.2.3` versioning tags

### ISSUE THREAD

**Issue by rpdelaney** [shanemadden/factorio-mod-portal-publish#2]
From [semver.org](https://semver.org):

> Q: Is “v1.2.3” a semantic version?
>
> A: No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

If you would accept a PR for this, I could put something together.

**Comment by shanemadden** [comment]
Sounds like a great feature, I wouldn't mind a PR if you've got the time to put one in - thanks!
